### ISSUE TITLE
Make Submerged source-available on GitHub

### ISSUE THREAD

**Issue by Alexejhero** [SubmergedAmongUs/Submerged#135]
I want to make this project source-available to allow others to contribute.

I will start by making the mod codebase source-available first, and then after a bit I will also do the same for the Unity project.

### Task list before making mod codebase source-available
[Target date: 3rd of March]
- [x] Figure out licensing

### Task list before making unity project source-available
 [Target date: ~~1st of April~~] Because of the Among Us update, I had to spend a lot of time working to update Submerged, so I won't have time to work on publishing the source of the Unity project. As such, I am delaying this until the 14th of April
- [x] Hollow out among us scripts and remove unused ones
- [x] Delete redundant/unused assets (including base-game shaders)

**Comment by Alexejhero** [comment]
The source code of the mod has been published, Unity project will follow soon

**Comment by GameTechGuides** [comment]
hey , if among us script aren't in submerged unity source it will impact submerged ? and why you are hollowing the among us script ? just keep them if possible

**Comment by Alexejhero** [comment]
it's taken me a little longer than I expected but progress is being made on the unity project, i'd say i'm about 70% done
